/** IANA timezone for common itinerary airports (extend as needed). */
const AIRPORT_TIMEZONES: Record<string, string> = {
  BOM: "Asia/Kolkata",
  DEL: "Asia/Kolkata",
  BLR: "Asia/Kolkata",
  MAA: "Asia/Kolkata",
  HYD: "Asia/Kolkata",
  CCU: "Asia/Kolkata",
  SIN: "Asia/Singapore",
  KUL: "Asia/Kuala_Lumpur",
  BKK: "Asia/Bangkok",
  HKG: "Asia/Hong_Kong",
  NRT: "Asia/Tokyo",
  HND: "Asia/Tokyo",
  ICN: "Asia/Seoul",
  DXB: "Asia/Dubai",
  DOH: "Asia/Qatar",
  MEL: "Australia/Melbourne",
  SYD: "Australia/Sydney",
  BNE: "Australia/Brisbane",
  PER: "Australia/Perth",
  ADL: "Australia/Adelaide",
  LST: "Australia/Hobart",
  HBA: "Australia/Hobart",
  AKL: "Pacific/Auckland",
  CHC: "Pacific/Auckland",
  LHR: "Europe/London",
  LGW: "Europe/London",
  CDG: "Europe/Paris",
  FRA: "Europe/Berlin",
  AMS: "Europe/Amsterdam",
  JFK: "America/New_York",
  EWR: "America/New_York",
  LGA: "America/New_York",
  PHL: "America/New_York",
  BOS: "America/New_York",
  IAD: "America/New_York",
  DCA: "America/New_York",
  ORD: "America/Chicago",
  DFW: "America/Chicago",
  DEN: "America/Denver",
  LAX: "America/Los_Angeles",
  SFO: "America/Los_Angeles",
  SEA: "America/Los_Angeles",
  LAS: "America/Los_Angeles",
  MIA: "America/New_York",
  ATL: "America/New_York",
  YYZ: "America/Toronto",
  YUL: "America/Toronto",
  YVR: "America/Vancouver",
  SLC: "America/Denver",
};

export function getAirportTimezone(iata?: string | null): string | null {
  if (!iata) return null;
  return AIRPORT_TIMEZONES[iata.trim().toUpperCase()] ?? null;
}
